roi_bed: /Users/josephhalstead/Documents/gel_vcf_filtering/config/beds/truseq-exome-targeted-regions-manifest-v1-2.bed

families:
  FAM001: [LP3000972-DNA_H03_LP3000972-DNA_H03, LP3000972-DNA_H03_LP3000962-DNA_B01, LP3000972-DNA_H03_LP3000992-DNA_G08]

reference: /Users/josephhalstead/Documents/genomics_resources/refs/Homo_sapiens.GRCh38.dna.primary_assembly.fa.gz

vep_cache_location: /Users/josephhalstead/Documents/genomics_resources/vep_refseq_38

gnomad_genomes: /Users/josephhalstead/Documents/genomics_resources/snps/gnomad.genomes.r2.0.1.sites.GRCh38.noVEP.vcf.gz

gnomad_exomes: /Users/josephhalstead/Documents/genomics_resources/snps/gnomad.exomes.r2.0.1.sites.GRCh38.noVEP.vcf.gz

ccrs: /Users/josephhalstead/Documents/genomics_resources/beds/ccrs.all.v2.20180420_38.bed.gz

spliceai: test

vep_threads: 1

sample_info:
    LP3000972-DNA_H03:
      familyId: FAM001
      maternalId: LP3000992-DNA_G08
      paternalId: LP3000962-DNA_B01
      phenotype: 2
      sex: '1'
      worklistId: '123000009'
    LP3000992-DNA_G08:
      familyId: FAM001
      maternalId: null
      paternalId: null
      phenotype: 1
      sex: '2'
      worklistId: '123000009'
    LP3000962-DNA_B01:
      familyId: FAM001
      maternalId: null
      paternalId: null
      phenotype: 1
      sex: '1'
      worklistId: '123000009'